@echo off  
mkdir src\components\common src\components\import src\components\export src\components\layout src\pages src\hooks src\services src\utils src\contexts src\styles\components src\assets\icons src\assets\images src\assets\sample-data src\config 2>nul  
type nul > src\components\common\Button.jsx  
type nul > src\components\common\Input.jsx  
type nul > src\components\common\Modal.jsx  
type nul > src\components\common\Card.jsx  
type nul > src\components\common\Loader.jsx  
type nul > src\components\import\ImportWizard.jsx  
type nul > src\components\import\FileUploader.jsx  
type nul > src\components\import\DataPreview.jsx  
type nul > src\components\import\ColumnMapper.jsx  
type nul > src\components\import\ImportSummary.jsx  
type nul > src\components\export\ExportWizard.jsx  
type nul > src\components\export\FormatSelector.jsx  
type nul > src\components\export\FieldSelector.jsx  
type nul > src\components\export\FilterBuilder.jsx  
type nul > src\components\export\ExportSummary.jsx  
type nul > src\components\layout\Header.jsx  
type nul > src\components\layout\Sidebar.jsx  
type nul > src\components\layout\Footer.jsx  
type nul > src\pages\Dashboard.jsx  
type nul > src\pages\ImportPage.jsx  
type nul > src\pages\ExportPage.jsx  
type nul > src\pages\HistoryPage.jsx  
type nul > src\pages\SettingsPage.jsx  
type nul > src\hooks\useFileUpload.js  
type nul > src\hooks\useImport.js  
type nul > src\hooks\useExport.js  
type nul > src\hooks\useDataValidation.js  
type nul > src\hooks\useLocalStorage.js  
type nul > src\services\fileParser.js  
type nul > src\services\dataTransformer.js  
type nul > src\services\validationRules.js  
type nul > src\services\exportFormatter.js  
type nul > src\services\storageService.js  
type nul > src\utils\constants.js  
type nul > src\utils\helpers.js  
type nul > src\utils\validators.js  
type nul > src\utils\formatters.js  
type nul > src\contexts\ImportContext.jsx  
type nul > src\contexts\ExportContext.jsx  
type nul > src\contexts\AppContext.jsx  
type nul > src\styles\globals.css  
type nul > src\styles\variables.css  
type nul > src\config\fileTypes.js  
type nul > src\config\exportFormats.js  
type nul > src\config\appConfig.js  
type nul > src\routes.jsx  
echo Structure created successfully! 
